###########
# site.title

title: Piumaster | Alejandro Piumetti
description: Lugar donde escribo cosas
# baseurl: "/jekyllBear" # the subpath of your site, e.g. /blog/
url: "https://alepiumetti.github.io" # the base hostname & protocol for your site
# host: 0.0.0.0


#########################
# more settings

plugins:
  - jekyll-redirect-from
  - jekyll-feed


feed:
  path: feed/blog.xml
  title: "Piumaster Blog | Alejandro Piumetti"
  description: "Blog posts feed"
  collections:
    journey:
      path: feed/journey.xml
      title: "Piumaster Journey | Alejandro Piumetti"
      description: "Journey feed"

whitelist:
  - jekyll-redirect-from

markdown: kramdown

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

# sass:
#   sass_dir: css
#   style:    compressed

collections:
  my_tags:
    output: true
    permalink: /tagged/:slug/
  journey:
    output: true
    permalink: /journey/:title/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: tagged

# baseurl: ""
permalink: /blog/:slug
timezone: America/New_York
future: false

exclude:
- README.md
- LICENSE.md

exclude: [vendor]

Blog: /blog
Journey: /journey

# Add general links to site pages here

# Add links for more focus here
special_links:
  "Github": https://github.com/alepiumetti
  "LinkedIn": https://www.linkedin.com/in/alejandro-piumetti/